version: 2 
 
sources: 
  - name: raw
    schema: ml_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns: 
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: Foreign key to ship
          - name: products_id
            description: Foreign key to product
          - name: revenue
            description: Revenu of sale
          - name: quantity
            description: Quantity of sale
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns: 
          - name: products_id
            description: Primary key of table 'product'
            tests: 
              - unique 
              - not_null
          - name: purchase_price
            description: Price of purchase
      - name: ship
        identifier: raw_gz_ship
        description: ships of Greenweez
        columns: 
          - name: orders_id
            description: Foreign key to ship
            tests: 
              - unique 
              - not_null
          - name: shipping_fee
            description: Taxe of ship
          - name: logCost
            description: Cost log
          - name: ship_cost
            description: Price of purchase